# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/Project/zwave-automation-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Project/zwave-automation-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/alex/Project/zwave-automation-engine/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Project/zwave-automation-engine/CMakeFiles /home/alex/Project/zwave-automation-engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Project/zwave-automation-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named zwave-automation-engine

# Build rule for target.
zwave-automation-engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zwave-automation-engine
.PHONY : zwave-automation-engine

# fast build rule for target.
zwave-automation-engine/fast:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/build
.PHONY : zwave-automation-engine/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ZaeUtil

# Build rule for target.
ZaeUtil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZaeUtil
.PHONY : ZaeUtil

# fast build rule for target.
ZaeUtil/fast:
	$(MAKE) -f libZaeUtil/CMakeFiles/ZaeUtil.dir/build.make libZaeUtil/CMakeFiles/ZaeUtil.dir/build
.PHONY : ZaeUtil/fast

#=============================================================================
# Target rules for targets named Cron

# Build rule for target.
Cron: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Cron
.PHONY : Cron

# fast build rule for target.
Cron/fast:
	$(MAKE) -f services/Cron/CMakeFiles/Cron.dir/build.make services/Cron/CMakeFiles/Cron.dir/build
.PHONY : Cron/fast

#=============================================================================
# Target rules for targets named DateTime

# Build rule for target.
DateTime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DateTime
.PHONY : DateTime

# fast build rule for target.
DateTime/fast:
	$(MAKE) -f services/DateTime/CMakeFiles/DateTime.dir/build.make services/DateTime/CMakeFiles/DateTime.dir/build
.PHONY : DateTime/fast

#=============================================================================
# Target rules for targets named IFTTT

# Build rule for target.
IFTTT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IFTTT
.PHONY : IFTTT

# fast build rule for target.
IFTTT/fast:
	$(MAKE) -f services/IFTTT/CMakeFiles/IFTTT.dir/build.make services/IFTTT/CMakeFiles/IFTTT.dir/build
.PHONY : IFTTT/fast

#=============================================================================
# Target rules for targets named Mail

# Build rule for target.
Mail: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Mail
.PHONY : Mail

# fast build rule for target.
Mail/fast:
	$(MAKE) -f services/Mail/CMakeFiles/Mail.dir/build.make services/Mail/CMakeFiles/Mail.dir/build
.PHONY : Mail/fast

#=============================================================================
# Target rules for targets named SMS

# Build rule for target.
SMS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SMS
.PHONY : SMS

# fast build rule for target.
SMS/fast:
	$(MAKE) -f services/SMS/CMakeFiles/SMS.dir/build.make services/SMS/CMakeFiles/SMS.dir/build
.PHONY : SMS/fast

#=============================================================================
# Target rules for targets named Timer

# Build rule for target.
Timer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Timer
.PHONY : Timer

# fast build rule for target.
Timer/fast:
	$(MAKE) -f services/Timer/CMakeFiles/Timer.dir/build.make services/Timer/CMakeFiles/Timer.dir/build
.PHONY : Timer/fast

#=============================================================================
# Target rules for targets named Weather

# Build rule for target.
Weather: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Weather
.PHONY : Weather

# fast build rule for target.
Weather/fast:
	$(MAKE) -f services/Weather/CMakeFiles/Weather.dir/build.make services/Weather/CMakeFiles/Weather.dir/build
.PHONY : Weather/fast

#=============================================================================
# Target rules for targets named BlinkCamera

# Build rule for target.
BlinkCamera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlinkCamera
.PHONY : BlinkCamera

# fast build rule for target.
BlinkCamera/fast:
	$(MAKE) -f vdev/BlinkCamera/CMakeFiles/BlinkCamera.dir/build.make vdev/BlinkCamera/CMakeFiles/BlinkCamera.dir/build
.PHONY : BlinkCamera/fast

#=============================================================================
# Target rules for targets named Button

# Build rule for target.
Button: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Button
.PHONY : Button

# fast build rule for target.
Button/fast:
	$(MAKE) -f vdev/Button/CMakeFiles/Button.dir/build.make vdev/Button/CMakeFiles/Button.dir/build
.PHONY : Button/fast

#=============================================================================
# Target rules for targets named SecuritySystem

# Build rule for target.
SecuritySystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SecuritySystem
.PHONY : SecuritySystem

# fast build rule for target.
SecuritySystem/fast:
	$(MAKE) -f vdev/SecuritySystem/CMakeFiles/SecuritySystem.dir/build.make vdev/SecuritySystem/CMakeFiles/SecuritySystem.dir/build
.PHONY : SecuritySystem/fast

#=============================================================================
# Target rules for targets named Sensor

# Build rule for target.
Sensor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sensor
.PHONY : Sensor

# fast build rule for target.
Sensor/fast:
	$(MAKE) -f vdev/Sensor/CMakeFiles/Sensor.dir/build.make vdev/Sensor/CMakeFiles/Sensor.dir/build
.PHONY : Sensor/fast

#=============================================================================
# Target rules for targets named SurveillanceStation

# Build rule for target.
SurveillanceStation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SurveillanceStation
.PHONY : SurveillanceStation

# fast build rule for target.
SurveillanceStation/fast:
	$(MAKE) -f vdev/SurveillanceStation/CMakeFiles/SurveillanceStation.dir/build.make vdev/SurveillanceStation/CMakeFiles/SurveillanceStation.dir/build
.PHONY : SurveillanceStation/fast

#=============================================================================
# Target rules for targets named scripts

# Build rule for target.
scripts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scripts
.PHONY : scripts

# fast build rule for target.
scripts/fast:
	$(MAKE) -f scripts/CMakeFiles/scripts.dir/build.make scripts/CMakeFiles/scripts.dir/build
.PHONY : scripts/fast

#=============================================================================
# Target rules for targets named homebridge-zae

# Build rule for target.
homebridge-zae: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 homebridge-zae
.PHONY : homebridge-zae

# fast build rule for target.
homebridge-zae/fast:
	$(MAKE) -f homebridge-zae/CMakeFiles/homebridge-zae.dir/build.make homebridge-zae/CMakeFiles/homebridge-zae.dir/build
.PHONY : homebridge-zae/fast

BuiltinServices/Conditional.o: BuiltinServices/Conditional.c.o

.PHONY : BuiltinServices/Conditional.o

# target to build an object file
BuiltinServices/Conditional.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Conditional.c.o
.PHONY : BuiltinServices/Conditional.c.o

BuiltinServices/Conditional.i: BuiltinServices/Conditional.c.i

.PHONY : BuiltinServices/Conditional.i

# target to preprocess a source file
BuiltinServices/Conditional.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Conditional.c.i
.PHONY : BuiltinServices/Conditional.c.i

BuiltinServices/Conditional.s: BuiltinServices/Conditional.c.s

.PHONY : BuiltinServices/Conditional.s

# target to generate assembly for a file
BuiltinServices/Conditional.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Conditional.c.s
.PHONY : BuiltinServices/Conditional.c.s

BuiltinServices/EventLog.o: BuiltinServices/EventLog.c.o

.PHONY : BuiltinServices/EventLog.o

# target to build an object file
BuiltinServices/EventLog.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/EventLog.c.o
.PHONY : BuiltinServices/EventLog.c.o

BuiltinServices/EventLog.i: BuiltinServices/EventLog.c.i

.PHONY : BuiltinServices/EventLog.i

# target to preprocess a source file
BuiltinServices/EventLog.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/EventLog.c.i
.PHONY : BuiltinServices/EventLog.c.i

BuiltinServices/EventLog.s: BuiltinServices/EventLog.c.s

.PHONY : BuiltinServices/EventLog.s

# target to generate assembly for a file
BuiltinServices/EventLog.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/EventLog.c.s
.PHONY : BuiltinServices/EventLog.c.s

BuiltinServices/Expression.o: BuiltinServices/Expression.c.o

.PHONY : BuiltinServices/Expression.o

# target to build an object file
BuiltinServices/Expression.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Expression.c.o
.PHONY : BuiltinServices/Expression.c.o

BuiltinServices/Expression.i: BuiltinServices/Expression.c.i

.PHONY : BuiltinServices/Expression.i

# target to preprocess a source file
BuiltinServices/Expression.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Expression.c.i
.PHONY : BuiltinServices/Expression.c.i

BuiltinServices/Expression.s: BuiltinServices/Expression.c.s

.PHONY : BuiltinServices/Expression.s

# target to generate assembly for a file
BuiltinServices/Expression.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Expression.c.s
.PHONY : BuiltinServices/Expression.c.s

BuiltinServices/List.o: BuiltinServices/List.c.o

.PHONY : BuiltinServices/List.o

# target to build an object file
BuiltinServices/List.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/List.c.o
.PHONY : BuiltinServices/List.c.o

BuiltinServices/List.i: BuiltinServices/List.c.i

.PHONY : BuiltinServices/List.i

# target to preprocess a source file
BuiltinServices/List.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/List.c.i
.PHONY : BuiltinServices/List.c.i

BuiltinServices/List.s: BuiltinServices/List.c.s

.PHONY : BuiltinServices/List.s

# target to generate assembly for a file
BuiltinServices/List.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/List.c.s
.PHONY : BuiltinServices/List.c.s

BuiltinServices/Resolver.o: BuiltinServices/Resolver.c.o

.PHONY : BuiltinServices/Resolver.o

# target to build an object file
BuiltinServices/Resolver.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Resolver.c.o
.PHONY : BuiltinServices/Resolver.c.o

BuiltinServices/Resolver.i: BuiltinServices/Resolver.c.i

.PHONY : BuiltinServices/Resolver.i

# target to preprocess a source file
BuiltinServices/Resolver.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Resolver.c.i
.PHONY : BuiltinServices/Resolver.c.i

BuiltinServices/Resolver.s: BuiltinServices/Resolver.c.s

.PHONY : BuiltinServices/Resolver.s

# target to generate assembly for a file
BuiltinServices/Resolver.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/Resolver.c.s
.PHONY : BuiltinServices/Resolver.c.s

BuiltinServices/SensorEvent.o: BuiltinServices/SensorEvent.c.o

.PHONY : BuiltinServices/SensorEvent.o

# target to build an object file
BuiltinServices/SensorEvent.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/SensorEvent.c.o
.PHONY : BuiltinServices/SensorEvent.c.o

BuiltinServices/SensorEvent.i: BuiltinServices/SensorEvent.c.i

.PHONY : BuiltinServices/SensorEvent.i

# target to preprocess a source file
BuiltinServices/SensorEvent.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/SensorEvent.c.i
.PHONY : BuiltinServices/SensorEvent.c.i

BuiltinServices/SensorEvent.s: BuiltinServices/SensorEvent.c.s

.PHONY : BuiltinServices/SensorEvent.s

# target to generate assembly for a file
BuiltinServices/SensorEvent.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/BuiltinServices/SensorEvent.c.s
.PHONY : BuiltinServices/SensorEvent.c.s

builtin_service.o: builtin_service.c.o

.PHONY : builtin_service.o

# target to build an object file
builtin_service.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/builtin_service.c.o
.PHONY : builtin_service.c.o

builtin_service.i: builtin_service.c.i

.PHONY : builtin_service.i

# target to preprocess a source file
builtin_service.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/builtin_service.c.i
.PHONY : builtin_service.c.i

builtin_service.s: builtin_service.c.s

.PHONY : builtin_service.s

# target to generate assembly for a file
builtin_service.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/builtin_service.c.s
.PHONY : builtin_service.c.s

builtin_service_manager.o: builtin_service_manager.c.o

.PHONY : builtin_service_manager.o

# target to build an object file
builtin_service_manager.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/builtin_service_manager.c.o
.PHONY : builtin_service_manager.c.o

builtin_service_manager.i: builtin_service_manager.c.i

.PHONY : builtin_service_manager.i

# target to preprocess a source file
builtin_service_manager.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/builtin_service_manager.c.i
.PHONY : builtin_service_manager.c.i

builtin_service_manager.s: builtin_service_manager.c.s

.PHONY : builtin_service_manager.s

# target to generate assembly for a file
builtin_service_manager.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/builtin_service_manager.c.s
.PHONY : builtin_service_manager.c.s

cli_auth.o: cli_auth.c.o

.PHONY : cli_auth.o

# target to build an object file
cli_auth.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_auth.c.o
.PHONY : cli_auth.c.o

cli_auth.i: cli_auth.c.i

.PHONY : cli_auth.i

# target to preprocess a source file
cli_auth.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_auth.c.i
.PHONY : cli_auth.c.i

cli_auth.s: cli_auth.c.s

.PHONY : cli_auth.s

# target to generate assembly for a file
cli_auth.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_auth.c.s
.PHONY : cli_auth.c.s

cli_commands.o: cli_commands.c.o

.PHONY : cli_commands.o

# target to build an object file
cli_commands.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_commands.c.o
.PHONY : cli_commands.c.o

cli_commands.i: cli_commands.c.i

.PHONY : cli_commands.i

# target to preprocess a source file
cli_commands.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_commands.c.i
.PHONY : cli_commands.c.i

cli_commands.s: cli_commands.c.s

.PHONY : cli_commands.s

# target to generate assembly for a file
cli_commands.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_commands.c.s
.PHONY : cli_commands.c.s

cli_homebridge.o: cli_homebridge.c.o

.PHONY : cli_homebridge.o

# target to build an object file
cli_homebridge.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_homebridge.c.o
.PHONY : cli_homebridge.c.o

cli_homebridge.i: cli_homebridge.c.i

.PHONY : cli_homebridge.i

# target to preprocess a source file
cli_homebridge.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_homebridge.c.i
.PHONY : cli_homebridge.c.i

cli_homebridge.s: cli_homebridge.c.s

.PHONY : cli_homebridge.s

# target to generate assembly for a file
cli_homebridge.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_homebridge.c.s
.PHONY : cli_homebridge.c.s

cli_logger.o: cli_logger.c.o

.PHONY : cli_logger.o

# target to build an object file
cli_logger.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_logger.c.o
.PHONY : cli_logger.c.o

cli_logger.i: cli_logger.c.i

.PHONY : cli_logger.i

# target to preprocess a source file
cli_logger.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_logger.c.i
.PHONY : cli_logger.c.i

cli_logger.s: cli_logger.c.s

.PHONY : cli_logger.s

# target to generate assembly for a file
cli_logger.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_logger.c.s
.PHONY : cli_logger.c.s

cli_resolver.o: cli_resolver.c.o

.PHONY : cli_resolver.o

# target to build an object file
cli_resolver.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_resolver.c.o
.PHONY : cli_resolver.c.o

cli_resolver.i: cli_resolver.c.i

.PHONY : cli_resolver.i

# target to preprocess a source file
cli_resolver.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_resolver.c.i
.PHONY : cli_resolver.c.i

cli_resolver.s: cli_resolver.c.s

.PHONY : cli_resolver.s

# target to generate assembly for a file
cli_resolver.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_resolver.c.s
.PHONY : cli_resolver.c.s

cli_rest.o: cli_rest.c.o

.PHONY : cli_rest.o

# target to build an object file
cli_rest.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_rest.c.o
.PHONY : cli_rest.c.o

cli_rest.i: cli_rest.c.i

.PHONY : cli_rest.i

# target to preprocess a source file
cli_rest.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_rest.c.i
.PHONY : cli_rest.c.i

cli_rest.s: cli_rest.c.s

.PHONY : cli_rest.s

# target to generate assembly for a file
cli_rest.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_rest.c.s
.PHONY : cli_rest.c.s

cli_scene.o: cli_scene.c.o

.PHONY : cli_scene.o

# target to build an object file
cli_scene.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_scene.c.o
.PHONY : cli_scene.c.o

cli_scene.i: cli_scene.c.i

.PHONY : cli_scene.i

# target to preprocess a source file
cli_scene.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_scene.c.i
.PHONY : cli_scene.c.i

cli_scene.s: cli_scene.c.s

.PHONY : cli_scene.s

# target to generate assembly for a file
cli_scene.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_scene.c.s
.PHONY : cli_scene.c.s

cli_sensor.o: cli_sensor.c.o

.PHONY : cli_sensor.o

# target to build an object file
cli_sensor.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_sensor.c.o
.PHONY : cli_sensor.c.o

cli_sensor.i: cli_sensor.c.i

.PHONY : cli_sensor.i

# target to preprocess a source file
cli_sensor.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_sensor.c.i
.PHONY : cli_sensor.c.i

cli_sensor.s: cli_sensor.c.s

.PHONY : cli_sensor.s

# target to generate assembly for a file
cli_sensor.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_sensor.c.s
.PHONY : cli_sensor.c.s

cli_service.o: cli_service.c.o

.PHONY : cli_service.o

# target to build an object file
cli_service.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_service.c.o
.PHONY : cli_service.c.o

cli_service.i: cli_service.c.i

.PHONY : cli_service.i

# target to preprocess a source file
cli_service.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_service.c.i
.PHONY : cli_service.c.i

cli_service.s: cli_service.c.s

.PHONY : cli_service.s

# target to generate assembly for a file
cli_service.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_service.c.s
.PHONY : cli_service.c.s

cli_vdev.o: cli_vdev.c.o

.PHONY : cli_vdev.o

# target to build an object file
cli_vdev.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_vdev.c.o
.PHONY : cli_vdev.c.o

cli_vdev.i: cli_vdev.c.i

.PHONY : cli_vdev.i

# target to preprocess a source file
cli_vdev.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_vdev.c.i
.PHONY : cli_vdev.c.i

cli_vdev.s: cli_vdev.c.s

.PHONY : cli_vdev.s

# target to generate assembly for a file
cli_vdev.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/cli_vdev.c.s
.PHONY : cli_vdev.c.s

command_class.o: command_class.c.o

.PHONY : command_class.o

# target to build an object file
command_class.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/command_class.c.o
.PHONY : command_class.c.o

command_class.i: command_class.c.i

.PHONY : command_class.i

# target to preprocess a source file
command_class.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/command_class.c.i
.PHONY : command_class.c.i

command_class.s: command_class.c.s

.PHONY : command_class.s

# target to generate assembly for a file
command_class.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/command_class.c.s
.PHONY : command_class.c.s

command_parser.o: command_parser.c.o

.PHONY : command_parser.o

# target to build an object file
command_parser.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/command_parser.c.o
.PHONY : command_parser.c.o

command_parser.i: command_parser.c.i

.PHONY : command_parser.i

# target to preprocess a source file
command_parser.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/command_parser.c.i
.PHONY : command_parser.c.i

command_parser.s: command_parser.c.s

.PHONY : command_parser.s

# target to generate assembly for a file
command_parser.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/command_parser.c.s
.PHONY : command_parser.c.s

config.o: config.c.o

.PHONY : config.o

# target to build an object file
config.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/config.c.o
.PHONY : config.c.o

config.i: config.c.i

.PHONY : config.i

# target to preprocess a source file
config.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/config.c.i
.PHONY : config.c.i

config.s: config.c.s

.PHONY : config.s

# target to generate assembly for a file
config.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/config.c.s
.PHONY : config.c.s

data_callbacks.o: data_callbacks.c.o

.PHONY : data_callbacks.o

# target to build an object file
data_callbacks.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/data_callbacks.c.o
.PHONY : data_callbacks.c.o

data_callbacks.i: data_callbacks.c.i

.PHONY : data_callbacks.i

# target to preprocess a source file
data_callbacks.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/data_callbacks.c.i
.PHONY : data_callbacks.c.i

data_callbacks.s: data_callbacks.c.s

.PHONY : data_callbacks.s

# target to generate assembly for a file
data_callbacks.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/data_callbacks.c.s
.PHONY : data_callbacks.c.s

device_callbacks.o: device_callbacks.c.o

.PHONY : device_callbacks.o

# target to build an object file
device_callbacks.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/device_callbacks.c.o
.PHONY : device_callbacks.c.o

device_callbacks.i: device_callbacks.c.i

.PHONY : device_callbacks.i

# target to preprocess a source file
device_callbacks.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/device_callbacks.c.i
.PHONY : device_callbacks.c.i

device_callbacks.s: device_callbacks.c.s

.PHONY : device_callbacks.s

# target to generate assembly for a file
device_callbacks.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/device_callbacks.c.s
.PHONY : device_callbacks.c.s

homebridge_manager.o: homebridge_manager.c.o

.PHONY : homebridge_manager.o

# target to build an object file
homebridge_manager.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/homebridge_manager.c.o
.PHONY : homebridge_manager.c.o

homebridge_manager.i: homebridge_manager.c.i

.PHONY : homebridge_manager.i

# target to preprocess a source file
homebridge_manager.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/homebridge_manager.c.i
.PHONY : homebridge_manager.c.i

homebridge_manager.s: homebridge_manager.c.s

.PHONY : homebridge_manager.s

# target to generate assembly for a file
homebridge_manager.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/homebridge_manager.c.s
.PHONY : homebridge_manager.c.s

http_server.o: http_server.c.o

.PHONY : http_server.o

# target to build an object file
http_server.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/http_server.c.o
.PHONY : http_server.c.o

http_server.i: http_server.c.i

.PHONY : http_server.i

# target to preprocess a source file
http_server.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/http_server.c.i
.PHONY : http_server.c.i

http_server.s: http_server.c.s

.PHONY : http_server.s

# target to generate assembly for a file
http_server.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/http_server.c.s
.PHONY : http_server.c.s

logging_modules.o: logging_modules.c.o

.PHONY : logging_modules.o

# target to build an object file
logging_modules.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/logging_modules.c.o
.PHONY : logging_modules.c.o

logging_modules.i: logging_modules.c.i

.PHONY : logging_modules.i

# target to preprocess a source file
logging_modules.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/logging_modules.c.i
.PHONY : logging_modules.c.i

logging_modules.s: logging_modules.c.s

.PHONY : logging_modules.s

# target to generate assembly for a file
logging_modules.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/logging_modules.c.s
.PHONY : logging_modules.c.s

operator.o: operator.c.o

.PHONY : operator.o

# target to build an object file
operator.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/operator.c.o
.PHONY : operator.c.o

operator.i: operator.c.i

.PHONY : operator.i

# target to preprocess a source file
operator.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/operator.c.i
.PHONY : operator.c.i

operator.s: operator.c.s

.PHONY : operator.s

# target to generate assembly for a file
operator.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/operator.c.s
.PHONY : operator.c.s

parser_dfa.o: parser_dfa.c.o

.PHONY : parser_dfa.o

# target to build an object file
parser_dfa.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/parser_dfa.c.o
.PHONY : parser_dfa.c.o

parser_dfa.i: parser_dfa.c.i

.PHONY : parser_dfa.i

# target to preprocess a source file
parser_dfa.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/parser_dfa.c.i
.PHONY : parser_dfa.c.i

parser_dfa.s: parser_dfa.c.s

.PHONY : parser_dfa.s

# target to generate assembly for a file
parser_dfa.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/parser_dfa.c.s
.PHONY : parser_dfa.c.s

picohttpparser.o: picohttpparser.c.o

.PHONY : picohttpparser.o

# target to build an object file
picohttpparser.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/picohttpparser.c.o
.PHONY : picohttpparser.c.o

picohttpparser.i: picohttpparser.c.i

.PHONY : picohttpparser.i

# target to preprocess a source file
picohttpparser.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/picohttpparser.c.i
.PHONY : picohttpparser.c.i

picohttpparser.s: picohttpparser.c.s

.PHONY : picohttpparser.s

# target to generate assembly for a file
picohttpparser.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/picohttpparser.c.s
.PHONY : picohttpparser.c.s

python_command.o: python_command.c.o

.PHONY : python_command.o

# target to build an object file
python_command.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_command.c.o
.PHONY : python_command.c.o

python_command.i: python_command.c.i

.PHONY : python_command.i

# target to preprocess a source file
python_command.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_command.c.i
.PHONY : python_command.c.i

python_command.s: python_command.c.s

.PHONY : python_command.s

# target to generate assembly for a file
python_command.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_command.c.s
.PHONY : python_command.c.s

python_events.o: python_events.c.o

.PHONY : python_events.o

# target to build an object file
python_events.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_events.c.o
.PHONY : python_events.c.o

python_events.i: python_events.c.i

.PHONY : python_events.i

# target to preprocess a source file
python_events.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_events.c.i
.PHONY : python_events.c.i

python_events.s: python_events.c.s

.PHONY : python_events.s

# target to generate assembly for a file
python_events.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_events.c.s
.PHONY : python_events.c.s

python_logging.o: python_logging.c.o

.PHONY : python_logging.o

# target to build an object file
python_logging.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_logging.c.o
.PHONY : python_logging.c.o

python_logging.i: python_logging.c.i

.PHONY : python_logging.i

# target to preprocess a source file
python_logging.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_logging.c.i
.PHONY : python_logging.c.i

python_logging.s: python_logging.c.s

.PHONY : python_logging.s

# target to generate assembly for a file
python_logging.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_logging.c.s
.PHONY : python_logging.c.s

python_manager.o: python_manager.c.o

.PHONY : python_manager.o

# target to build an object file
python_manager.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_manager.c.o
.PHONY : python_manager.c.o

python_manager.i: python_manager.c.i

.PHONY : python_manager.i

# target to preprocess a source file
python_manager.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_manager.c.i
.PHONY : python_manager.c.i

python_manager.s: python_manager.c.s

.PHONY : python_manager.s

# target to generate assembly for a file
python_manager.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/python_manager.c.s
.PHONY : python_manager.c.s

scene.o: scene.c.o

.PHONY : scene.o

# target to build an object file
scene.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene.c.o
.PHONY : scene.c.o

scene.i: scene.c.i

.PHONY : scene.i

# target to preprocess a source file
scene.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene.c.i
.PHONY : scene.c.i

scene.s: scene.c.s

.PHONY : scene.s

# target to generate assembly for a file
scene.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene.c.s
.PHONY : scene.c.s

scene_action.o: scene_action.c.o

.PHONY : scene_action.o

# target to build an object file
scene_action.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene_action.c.o
.PHONY : scene_action.c.o

scene_action.i: scene_action.c.i

.PHONY : scene_action.i

# target to preprocess a source file
scene_action.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene_action.c.i
.PHONY : scene_action.c.i

scene_action.s: scene_action.c.s

.PHONY : scene_action.s

# target to generate assembly for a file
scene_action.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene_action.c.s
.PHONY : scene_action.c.s

scene_manager.o: scene_manager.c.o

.PHONY : scene_manager.o

# target to build an object file
scene_manager.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene_manager.c.o
.PHONY : scene_manager.c.o

scene_manager.i: scene_manager.c.i

.PHONY : scene_manager.i

# target to preprocess a source file
scene_manager.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene_manager.c.i
.PHONY : scene_manager.c.i

scene_manager.s: scene_manager.c.s

.PHONY : scene_manager.s

# target to generate assembly for a file
scene_manager.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/scene_manager.c.s
.PHONY : scene_manager.c.s

script_action_handler.o: script_action_handler.c.o

.PHONY : script_action_handler.o

# target to build an object file
script_action_handler.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/script_action_handler.c.o
.PHONY : script_action_handler.c.o

script_action_handler.i: script_action_handler.c.i

.PHONY : script_action_handler.i

# target to preprocess a source file
script_action_handler.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/script_action_handler.c.i
.PHONY : script_action_handler.c.i

script_action_handler.s: script_action_handler.c.s

.PHONY : script_action_handler.s

# target to generate assembly for a file
script_action_handler.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/script_action_handler.c.s
.PHONY : script_action_handler.c.s

sensor_manager.o: sensor_manager.c.o

.PHONY : sensor_manager.o

# target to build an object file
sensor_manager.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/sensor_manager.c.o
.PHONY : sensor_manager.c.o

sensor_manager.i: sensor_manager.c.i

.PHONY : sensor_manager.i

# target to preprocess a source file
sensor_manager.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/sensor_manager.c.i
.PHONY : sensor_manager.c.i

sensor_manager.s: sensor_manager.c.s

.PHONY : sensor_manager.s

# target to generate assembly for a file
sensor_manager.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/sensor_manager.c.s
.PHONY : sensor_manager.c.s

service_manager.o: service_manager.c.o

.PHONY : service_manager.o

# target to build an object file
service_manager.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/service_manager.c.o
.PHONY : service_manager.c.o

service_manager.i: service_manager.c.i

.PHONY : service_manager.i

# target to preprocess a source file
service_manager.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/service_manager.c.i
.PHONY : service_manager.c.i

service_manager.s: service_manager.c.s

.PHONY : service_manager.s

# target to generate assembly for a file
service_manager.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/service_manager.c.s
.PHONY : service_manager.c.s

socket_io.o: socket_io.c.o

.PHONY : socket_io.o

# target to build an object file
socket_io.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/socket_io.c.o
.PHONY : socket_io.c.o

socket_io.i: socket_io.c.i

.PHONY : socket_io.i

# target to preprocess a source file
socket_io.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/socket_io.c.i
.PHONY : socket_io.c.i

socket_io.s: socket_io.c.s

.PHONY : socket_io.s

# target to generate assembly for a file
socket_io.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/socket_io.c.s
.PHONY : socket_io.c.s

user_manager.o: user_manager.c.o

.PHONY : user_manager.o

# target to build an object file
user_manager.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/user_manager.c.o
.PHONY : user_manager.c.o

user_manager.i: user_manager.c.i

.PHONY : user_manager.i

# target to preprocess a source file
user_manager.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/user_manager.c.i
.PHONY : user_manager.c.i

user_manager.s: user_manager.c.s

.PHONY : user_manager.s

# target to generate assembly for a file
user_manager.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/user_manager.c.s
.PHONY : user_manager.c.s

vdev_manager.o: vdev_manager.c.o

.PHONY : vdev_manager.o

# target to build an object file
vdev_manager.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/vdev_manager.c.o
.PHONY : vdev_manager.c.o

vdev_manager.i: vdev_manager.c.i

.PHONY : vdev_manager.i

# target to preprocess a source file
vdev_manager.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/vdev_manager.c.i
.PHONY : vdev_manager.c.i

vdev_manager.s: vdev_manager.c.s

.PHONY : vdev_manager.s

# target to generate assembly for a file
vdev_manager.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/vdev_manager.c.s
.PHONY : vdev_manager.c.s

vty_io.o: vty_io.c.o

.PHONY : vty_io.o

# target to build an object file
vty_io.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/vty_io.c.o
.PHONY : vty_io.c.o

vty_io.i: vty_io.c.i

.PHONY : vty_io.i

# target to preprocess a source file
vty_io.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/vty_io.c.i
.PHONY : vty_io.c.i

vty_io.s: vty_io.c.s

.PHONY : vty_io.s

# target to generate assembly for a file
vty_io.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/vty_io.c.s
.PHONY : vty_io.c.s

zwave-automation-engine.o: zwave-automation-engine.c.o

.PHONY : zwave-automation-engine.o

# target to build an object file
zwave-automation-engine.c.o:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/zwave-automation-engine.c.o
.PHONY : zwave-automation-engine.c.o

zwave-automation-engine.i: zwave-automation-engine.c.i

.PHONY : zwave-automation-engine.i

# target to preprocess a source file
zwave-automation-engine.c.i:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/zwave-automation-engine.c.i
.PHONY : zwave-automation-engine.c.i

zwave-automation-engine.s: zwave-automation-engine.c.s

.PHONY : zwave-automation-engine.s

# target to generate assembly for a file
zwave-automation-engine.c.s:
	$(MAKE) -f CMakeFiles/zwave-automation-engine.dir/build.make CMakeFiles/zwave-automation-engine.dir/zwave-automation-engine.c.s
.PHONY : zwave-automation-engine.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... zwave-automation-engine"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... package"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... Continuous"
	@echo "... NightlyBuild"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyMemCheck"
	@echo "... package_source"
	@echo "... ExperimentalStart"
	@echo "... ContinuousConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... test"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousStart"
	@echo "... ContinuousUpdate"
	@echo "... ZaeUtil"
	@echo "... Cron"
	@echo "... DateTime"
	@echo "... IFTTT"
	@echo "... Mail"
	@echo "... SMS"
	@echo "... Timer"
	@echo "... Weather"
	@echo "... BlinkCamera"
	@echo "... Button"
	@echo "... SecuritySystem"
	@echo "... Sensor"
	@echo "... SurveillanceStation"
	@echo "... scripts"
	@echo "... homebridge-zae"
	@echo "... BuiltinServices/Conditional.o"
	@echo "... BuiltinServices/Conditional.i"
	@echo "... BuiltinServices/Conditional.s"
	@echo "... BuiltinServices/EventLog.o"
	@echo "... BuiltinServices/EventLog.i"
	@echo "... BuiltinServices/EventLog.s"
	@echo "... BuiltinServices/Expression.o"
	@echo "... BuiltinServices/Expression.i"
	@echo "... BuiltinServices/Expression.s"
	@echo "... BuiltinServices/List.o"
	@echo "... BuiltinServices/List.i"
	@echo "... BuiltinServices/List.s"
	@echo "... BuiltinServices/Resolver.o"
	@echo "... BuiltinServices/Resolver.i"
	@echo "... BuiltinServices/Resolver.s"
	@echo "... BuiltinServices/SensorEvent.o"
	@echo "... BuiltinServices/SensorEvent.i"
	@echo "... BuiltinServices/SensorEvent.s"
	@echo "... builtin_service.o"
	@echo "... builtin_service.i"
	@echo "... builtin_service.s"
	@echo "... builtin_service_manager.o"
	@echo "... builtin_service_manager.i"
	@echo "... builtin_service_manager.s"
	@echo "... cli_auth.o"
	@echo "... cli_auth.i"
	@echo "... cli_auth.s"
	@echo "... cli_commands.o"
	@echo "... cli_commands.i"
	@echo "... cli_commands.s"
	@echo "... cli_homebridge.o"
	@echo "... cli_homebridge.i"
	@echo "... cli_homebridge.s"
	@echo "... cli_logger.o"
	@echo "... cli_logger.i"
	@echo "... cli_logger.s"
	@echo "... cli_resolver.o"
	@echo "... cli_resolver.i"
	@echo "... cli_resolver.s"
	@echo "... cli_rest.o"
	@echo "... cli_rest.i"
	@echo "... cli_rest.s"
	@echo "... cli_scene.o"
	@echo "... cli_scene.i"
	@echo "... cli_scene.s"
	@echo "... cli_sensor.o"
	@echo "... cli_sensor.i"
	@echo "... cli_sensor.s"
	@echo "... cli_service.o"
	@echo "... cli_service.i"
	@echo "... cli_service.s"
	@echo "... cli_vdev.o"
	@echo "... cli_vdev.i"
	@echo "... cli_vdev.s"
	@echo "... command_class.o"
	@echo "... command_class.i"
	@echo "... command_class.s"
	@echo "... command_parser.o"
	@echo "... command_parser.i"
	@echo "... command_parser.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... data_callbacks.o"
	@echo "... data_callbacks.i"
	@echo "... data_callbacks.s"
	@echo "... device_callbacks.o"
	@echo "... device_callbacks.i"
	@echo "... device_callbacks.s"
	@echo "... homebridge_manager.o"
	@echo "... homebridge_manager.i"
	@echo "... homebridge_manager.s"
	@echo "... http_server.o"
	@echo "... http_server.i"
	@echo "... http_server.s"
	@echo "... logging_modules.o"
	@echo "... logging_modules.i"
	@echo "... logging_modules.s"
	@echo "... operator.o"
	@echo "... operator.i"
	@echo "... operator.s"
	@echo "... parser_dfa.o"
	@echo "... parser_dfa.i"
	@echo "... parser_dfa.s"
	@echo "... picohttpparser.o"
	@echo "... picohttpparser.i"
	@echo "... picohttpparser.s"
	@echo "... python_command.o"
	@echo "... python_command.i"
	@echo "... python_command.s"
	@echo "... python_events.o"
	@echo "... python_events.i"
	@echo "... python_events.s"
	@echo "... python_logging.o"
	@echo "... python_logging.i"
	@echo "... python_logging.s"
	@echo "... python_manager.o"
	@echo "... python_manager.i"
	@echo "... python_manager.s"
	@echo "... scene.o"
	@echo "... scene.i"
	@echo "... scene.s"
	@echo "... scene_action.o"
	@echo "... scene_action.i"
	@echo "... scene_action.s"
	@echo "... scene_manager.o"
	@echo "... scene_manager.i"
	@echo "... scene_manager.s"
	@echo "... script_action_handler.o"
	@echo "... script_action_handler.i"
	@echo "... script_action_handler.s"
	@echo "... sensor_manager.o"
	@echo "... sensor_manager.i"
	@echo "... sensor_manager.s"
	@echo "... service_manager.o"
	@echo "... service_manager.i"
	@echo "... service_manager.s"
	@echo "... socket_io.o"
	@echo "... socket_io.i"
	@echo "... socket_io.s"
	@echo "... user_manager.o"
	@echo "... user_manager.i"
	@echo "... user_manager.s"
	@echo "... vdev_manager.o"
	@echo "... vdev_manager.i"
	@echo "... vdev_manager.s"
	@echo "... vty_io.o"
	@echo "... vty_io.i"
	@echo "... vty_io.s"
	@echo "... zwave-automation-engine.o"
	@echo "... zwave-automation-engine.i"
	@echo "... zwave-automation-engine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

